### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by saucetray** [msoucy/Dotfiles#1]
I pulled your thing but there is no ./setup. Pls help - Fellow CSHER

**Comment by msoucy** [comment]
Fixed the readme - run `usesh/use` followed by the names of some of the directories within `files/`

**Comment by saucetray** [comment]
Is there a way to do this on MacOS?

**Comment by msoucy** [comment]
You should be able to install GNU Stow with `brew install stow`, however more than that I'm not too sure. I don't run MacOS.

**Comment by saucetray** [comment]
Thanksss

**Comment by rbuzzell** [comment]
It looks like the `readlink` command fulfills an entirely different function on macOS than on a Linux system.

**Comment by saucetray** [comment]
god damnit I thought unix was the same 😢

**Comment by msoucy** [comment]
Thanks macOS...
